###
POST http://localhost:3000/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


### asdfas

PUT http://localhost:3000/layers HTTP/1.1

content-type: application/json
{
    "name": "samplexx",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

