import PropTypes from 'prop-types'
import React from 'react'
import AutoComplete from 'material-ui/AutoComplete'

const vo = {
  BV: [
    'Vikertjernet',
    'Andersdammen',
    'Verkenslund',
    'Bangtjernet',
    'sebutjernet',
    'Klosterallen'
  ],
  BVV: [
    'Kvamsholman',
    'Sklinnaflesin',
    'Sklinnaflesin',
    'Ytre Brosmflesa',
    'Tronflesa',
    'Kjlsvikholmen',
    'Litlholmen',
    'Smskjera og Storholmen',
    'Smskjera og Storholmen',
    'Sandvikholman',
    'Finse',
    'Brennevinsholmen stre',
    'Btholmane',
    'Fantholmane-Matls',
    'Flakvarpholmen',
    'Kisteholmen',
    'Korset',
    'Fantholmane-Matls',
    'Soppekilen',
    'Soppekilen',
    'Demmekilskjra',
    'Hjelpskjra',
    'Saltskjr',
    'Steinene',
    'Nordre Fugleskjr',
    'Sauedauen',
    'Knubben',
    'Gseskjr',
    'Store Mkkalasset',
    'Bjrneskjr',
    'stre Rdskjr',
    'Store Danmarkskjr',
    'Kuskjra',
    'Haslau',
    'Skorpen',
    'Galteskjr',
    'Nakkeskjr',
    'Dokkskjret',
    'Stakaskjr',
    'styskjret',
    'Kausen',
    'Torskerumpa',
    'Sundskjra',
    'Strmsundholmen',
    'Flatholmen',
    'Saltbuskjr',
    'Gryteskjr',
    'Grtterdskjr',
    'Bueskjr',
    'Bjnnesholmen',
    'Bjnnesholmen',
    'Bekkeskjret',
    'Teineskjr',
    'Torbudalen',
    'Sandgrovbotn-Mardalsbotn',
    'Steinsbuskardet-Hisdal',
    'Steinsbuskardet-Hisdal',
    'Holmavassno'
  ],
  D: [
    'Kirkeneshalvya',
    'Karlsyvr',
    'Kristiansand kommuneskog',
    'Rysjen',
    'Borgan og Frelsy',
    'Runde',
    'Bergens fjellstrekninger',
    'Ullasundet',
    'Tyrifjorden',
    'Grimstadvatn',
    'Surna',
    'Djupvikvatnet-Kringlevatnet',
    'Lvsyrevet',
    'Vret',
    'Borgan og Frelsy',
    'Holme i Heggjadalsvann (Frislidvatnet)',
    'Storevik',
    'Malesanden og Huse',
    'Giske',
    'Aureosen',
    'Kvaly og Rauy',
    'Mellandsvgen',
    'rstad',
    'Landavatnet',
    'Orrevatnet',
    'Orrevatnet',
    'Orrevatnet',
    'Fl',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Froan',
    'Herdla',
    'Bliksvr',
    'Heglane og Eime',
    'Jndalssen med flere tjern og vann',
    'Vorma',
    'Andelven, Nessa og Risa'
  ],
  DO: [
    'Eggya',
    'Lille Follesya',
    'Lnan, Flovr og Skjrvr',
    'Lnan, Flovr og Skjrvr',
    'Lnan, Flovr og Skjrvr',
    'Muddvret',
    'Hensteinen, Horsvret og Gimsan',
    'Hensteinen, Horsvret og Gimsan',
    'Hensteinen, Horsvret og Gimsan',
    'Fuglevika',
    'Nordhasselvika',
    'Lvsyrevet',
    'Eidsvatnet',
    'Loga',
    'Lyngs-Lysgrd',
    'Leknesyene',
    'Havika',
    'Nryane',
    'Ullasundet',
    'Lgendeltaet',
    'Runde',
    'Runde',
    'Kjnsyhopen',
    'Flakkan',
    'Aureosen',
    'Runde',
    'Runde',
    'Mlen',
    'Lomendeltaet',
    'Helgetjnn',
    'Trettenstryka',
    'Bergsj-Hlandselva',
    'Nomevatn',
    'Rogneholmen',
    'Roaldsand',
    'Stokksund-Blikkvgane',
    'Rabukta',
    'Beengen',
    'Prestvannet',
    'Lundevgen',
    'Nautesund',
    'Aksevatnet',
    'Hafslovatnet',
    'Bukta',
    'Rrvikvgen',
    'Einsetvgen/Nsvatnet',
    'Malesanden og Huse',
    'Fluberg',
    'Rykenvika',
    'Sylteosen',
    'Malesanden og Huse',
    'Roaldsand',
    'Aureosen',
    'Giske',
    'Blindheimsvik',
    'Lvsyrevet',
    'Bingsholmsrsa',
    'Nedre Lyngdalselva',
    'Hovsfjra',
    'Innstrandfjra',
    'Krkvgsvaet',
    'Strmmen',
    'Figgaoset',
    'Skeisneset',
    'Bjortjnn',
    'Steinodden',
    'Osen',
    'Horta',
    'Lyngvret',
    'Lundleiret',
    'Vaggen',
    'Giplingya',
    'Tynesfjra',
    'Alnes',
    'Falstadbukta',
    'Vikaleiret',
    'Vinnan og Velvangen',
    'Nordre Rennesy',
    'Foldy',
    'Vignesholmane',
    'Lindy',
    'Fokksteinane',
    'Kjrholt',
    'Hyggen Mellom',
    'Solbergdammen',
    'Grnsanddammen',
    'Langsetdammen',
    'Fotlandsvatnet',
    'Stokkalandsvatnet',
    'Vikanbukta',
    'Kvistemyrdammen',
    'Blylagsdammen',
    'Tangendammen',
    'Eggholmane',
    'Ringsholmane',
    'Ringsholmane',
    'Vollsfjorden indre',
    'Vollsfjorden midtre',
    'Hvikskjra',
    'Gseskjra',
    'Grindskjr',
    'Skomakerskjra',
    'stre Utengskjr',
    'Kaffeskjr',
    'Rogneskjr',
    'Smskjr',
    'Flatskjr',
    'Tuskjr',
    'Storskjr',
    'Nordre Sauholmen',
    'Krkholmen',
    'Selskjr',
    'Hemskilen',
    'Hemskilen',
    'Hemskilen',
    'Hemskilen',
    'Langholmene',
    'Ferjeholmen',
    'Blene',
    'Ertholmen',
    'Lyngholmen',
    'Maryskjra',
    'Glomsteinskjr',
    'Gumserdya',
    'Fl',
    'Flottin',
    'Grudevatn',
    'Jrstrendene',
    'Jrstrendene',
    'Jrstrendene',
    'Jrstrendene',
    'Jrstrendene',
    'Jrstrendene',
    'Jrstrendene',
    'Jrstrendene',
    'Svaet',
    'Svaet',
    'Vellamelen',
    'Bjrga',
    'Falkenstendammen',
    'Masssen',
    'Fitjan',
    'Grunnfr',
    'Taralden',
    'Eidsbotn',
    'Sndre Fryland'
  ],
  GVS: [
    'Festningen geotopvernomrde'
  ],
  LVO: [
    'Straumen',
    'Sandfjorden',
    'Straumen',
    'Auskarnes',
    'Vassbotndalen',
    'Brannsletta',
    'Risduottarhldi',
    'Listastrendene',
    'Aurmoen',
    'Kalkheia',
    'Aurmoen',
    'Frland/Sletthei',
    'Fritzehus',
    'Bokemoa',
    'Urdalen',
    'Hestad',
    'Vret',
    'Maridalen',
    'Kjenstad',
    'Listastrendene',
    'Listastrendene',
    'Hanangervann og Krkenesvann',
    'Elstad',
    'Elstad',
    'Frland/Sletthei',
    'Fjsanger',
    'Listastrendene',
    'Synesvarden',
    'Synesvarden',
    'Ultvedt',
    'Elstad',
    'Fjsanger',
    'Listastrendene',
    'Listastrendene',
    'Listastrendene',
    'Listastrendene',
    'Lyngaland',
    'Romerike',
    'Aurmoen',
    'Berge',
    'Aurmoen',
    'Aurmoen',
    'Svareidberget',
    'sthagan',
    'Vey',
    'Nedre Hassel',
    'Havnehagen',
    'Elstad',
    'Kolss/Dlivann',
    'Vormedalsheia',
    'Skaupsjen/Hardangerjkulen',
    'Msvatn Austfjell',
    'Fdalen',
    'Hodalen',
    'Rokke',
    'Listastrendene',
    'Femundslia',
    'Langtjnna',
    'Austre Tiplingan/Luvlie Diehpell',
    'Oksevatnet',
    'Teistevika',
    'Tjuvdalen',
    'Kvitsanden',
    'Flekkefjord',
    'nesdalen',
    'Bondhusdalen',
    'Hattebergsdalen',
    'Buer',
    'Oksy-Ryvingen',
    'Mysalen',
    'Stlsheimen',
    'Hovedya',
    'Hovedya',
    'Dividalen',
    'Hydalen',
    'Svartskog',
    'Nordkvalya - Rebbenesya',
    'Naustdal-Gjengedal',
    'Strauman',
    'Skardsfjella og Hyllingsdalen',
    'Blankvann',
    'Kvnangsbotn',
    'Navitdalen',
    'Storlgeret',
    'Espedalen',
    'Haldorbu',
    'Dokkfaret',
    'Persfjorden-Syltefjorden',
    'Persfjorden-Syltefjorden',
    'Nordbytjern',
    'Tranby',
    'Tranby',
    'Jrstrendene',
    'Jrstrendene',
    'Austrttlunden',
    'Austrttlunden',
    'Forddalen',
    'Londalen-rvilldalen',
    'Magnilldalen-Busjdalen',
    'Endalen',
    'Budalen',
    'yungen',
    'Vangrftdalen-Kjurrudalen',
    'Utladalen',
    'Knutsh',
    'Knutsh',
    'motan-Grvudalen',
    'motan-Grvudalen',
    'motan-Grvudalen',
    'Eikesdalsvatnet',
    'Grimsdalen',
    'Grimsdalen',
    'Eikesdalsvatnet',
    'Dalsida',
    'motsdalen',
    'Hjerkinn/Kongsvoll/Drivdalen',
    'Fokstugu',
    'Jora',
    'Frydalen',
    'Vesle Hjerkinn',
    'Drlen',
    'Finndalen',
    'Ottadalen',
    'Lordalen',
    'Trollstigen',
    'Romsdalen',
    'Tafjorden-Reindalen',
    'Saltfjellet',
    'Gsvatnan',
    'Lang',
    'Rd-Dirhue',
    'Garsjen',
    'Larvik bkeskog',
    'Skrimfjella',
    'Skrimfjella',
    'Skrimfjella',
    'Skjkra',
    'Slen',
    'Trollheimen',
    'Trollheimen',
    'Innerdalen',
    'Frafjordheiane',
    'Hovden',
    'Lusaheia',
    'Lkeneshalvya',
    'Dammane',
    'Berby',
    'Berby',
    'Berby',
    'Vassfaret og Vidalen',
    'Indre Vassfaret',
    'Eikefjelldalen',
    'Vingen',
    'Nryfjorden',
    'Bleia-Storebotnen',
    'lfotbreen',
    'Geiranger-Herdalen',
    'Hydalen',
    'Mysubytta',
    'Mrkridsdalen',
    'Strynefjellet',
    'Vigdalen',
    'Strholmen',
    'Strholmen',
    'Semsvannet',
    'Sm',
    'Sm',
    'Bilisen',
    'Lyngsalpan',
    'Lyngsalpan',
    'Sndre Jely',
    'Vrne Kloster',
    'Vikerya'
  ],
  LVOD: [
    'Glomdeltaet',
    'Prestvatn',
    'Skipsfjord',
    'Laugen',
    'svr',
    'Rstyan',
    'Borgvret',
    'Svellingsflaket',
    'Hysvr/Sla',
    'Msvasstangen',
    'Kalvya - Ytre Tronderya',
    'Fedjemyrane',
    'Msvatn Austfjell - Hondle',
    'rya',
    'Hekkingen',
    'Bergsyan',
    'Lemmingvr',
    'Hja-Rssholmen',
    'Edya',
    'Steinavr',
    'Flatya',
    'Flatya',
    'Holmenvr',
    'Hekkingen',
    'Hekkingen',
    'Hja-Rssholmen',
    'Hja-Rssholmen',
    'rya',
    'Store Risya',
    'Froan',
    'Favnvassdalen',
    'Brattefjell - Vindeggen',
    'Brattefjell - Vindeggen',
    'Mstadfjellet',
    'Setesdal Vesthei Ryfylkeheiane',
    'Setesdal Vesthei Ryfylkeheiane',
    'Sandebukta',
    'Strand/Os',
    'Sndre Fryland'
  ],
  LVOP: [
    'Stabbursdalen',
    'sterdalen',
    'Sandvret',
    'Synesvarden',
    'Storemyr - Fagerbakken',
    'lveshovda',
    'Gjuvslandslia',
    'Raudya',
    'Raudya',
    'Raudya',
    'Brandvik',
    'Hosensand',
    'Skorpa-Nklan',
    'Skorpa-Nklan',
    'Skorpa-Nklan',
    'Skorpa-Nklan',
    'Hovedya',
    'Hovedya',
    'Sylan',
    'Eldya-Sletter',
    'Blankvann',
    'Blankvann',
    'Blankvann',
    'Blankvann',
    'Ledalen',
    'ya/Langholmen',
    'Kvikkleiryran',
    'Kvanndalen',
    'Dyraheio',
    'vre Pasvik'
  ],
  LVOPD: [
    'Basty',
    'Rambjra',
    'Langya',
    'Haverya',
    'Sr-Smla',
    'Auesya'
  ],
  MAV: [
    'Tauterryggen',
    'Framvaren',
    'Framvaren',
    'Framvaren',
    'Saltstraumen',
    'Gaulosen',
    'Jrkysten',
    'Rdberget'
  ],
  MIV: [
    'Krakksfjellet',
    'Salomonbergan'
  ],
  NM: [
    'Bigganjarga',
    'Ullhaugtoppen',
    'Tnnerudtangen',
    'Jongssveien',
    'Linlandveien',
    'Vra',
    'Lven',
    'Torsnes',
    'Skudesundskjrene',
    'Ekebo/Eikheim',
    'Kongshavn',
    'Muttagruven',
    'Damtjern',
    'Labukta',
    'Bjerksholmveien',
    'Kutangen',
    'Bdalen',
    'Muggerudkleiva',
    'Helgja',
    'Lven',
    'Ekebo/Eikheim',
    'Kampebrten',
    'St. Olavsormen',
    'Austad',
    'Fjsanger',
    'Svedalen',
    'Tveithaugen',
    'Huk',
    'Heggelia',
    'Bjerksholmen',
    'Huk',
    'Cappelenbruddet',
    'Holmenskjr',
    'Killingen',
    'Vallerkroken',
    'Lven',
    'Skudesundskjrene',
    'Red',
    'rvollsen',
    'Grytting',
    'Muttatjern',
    'Skjerpemyr',
    'Garntangen',
    'Garntangen',
    'Krekling',
    'Haugnes',
    'Slemmestad',
    'Veldre',
    'Strmodden',
    'Ksene Nord',
    'Hrtekollen',
    'Sndre Nrsnes',
    'Nordre Nrsnes',
    'Krekling',
    'Krekling',
    'Skarra',
    'Garntangen',
    'Garntangen',
    'Kjellerberget',
    'Vesthagan',
    'Ksene Sr',
    'Vesthagan',
    'Simonsodden',
    'Tveithaugen',
    'Brnarsen',
    'Hoppestadelva',
    'Kapitelberget',
    'Skrapekleiv',
    'Veldre',
    'Ula',
    'Ula',
    'Domkirkeodden',
    'Jutulgrava',
    'Eksberget',
    'Tmten',
    'Moelv Brygge',
    'Rahaugen',
    'Bratthagen',
    'Lven',
    'Lven',
    'Lven',
    'Lven',
    'Lona',
    'Bjerkya',
    'Konglungen',
    'Neselva',
    'Presteskjr',
    'Kjrkjetangen',
    'Kremmerodden',
    'Kvitskriuprestin',
    'Kulpa',
    'Kjellsen',
    'Stokkesen',
    'Jrstrendene',
    'Jrstrendene',
    'Jrstrendene',
    'Jrstrendene',
    'Repparfjord',
    'Brtane',
    'Holden grd',
    'Malmya brygge'
  ],
  NP: [
    'vre Anarjokka',
    'Stabbursdalen',
    'Reisa',
    'Rago',
    'Hardangervidda',
    'Femundsmarka',
    'Brgefjell/Byrkije',
    'nderdalen',
    'Gutulia',
    'Folgefonna',
    'Mysalen',
    'Seiland',
    'vre Dividal',
    'Hallingskarvet',
    'Lomsdal-Visten',
    'Rohkunborri',
    'Langsua',
    'Varangerhalvya',
    'Fulufjellet',
    'Frder',
    'Forollhogna',
    'Sjunkhatten',
    'Lierne',
    'Jotunheimen',
    'Dovrefjell-Sunndalsfjella',
    'Dovrefjell-Sunndalsfjella',
    'Rondane',
    'Dovre',
    'Reinheimen',
    'Lhko',
    'Junkerdal',
    'Saltfjellet-Svartisen',
    'Blfjella-Skjkerfjella',
    'Ytre Hvaler',
    'Breheimen',
    'Breheimen',
    'Jostedalsbreen',
    'Jomfruland',
    'Raet',
    'vre Pasvik',
    'Skarvan og Roltdalen'
  ],
  NPS: [
    'Sassen-Bnsow Land nasjonalpark',
    'Sr-Spitsbergen nasjonalpark',
    'Nordenskild Land nasjonalpark',
    'Forlandet nasjonalpark',
    'Nordvest-Spitsbergen nasjonalpark',
    'Indre Wijdefjorden nasjonalpark',
    'Nordre Isfjorden nasjonalpark'
  ],
  NR: [
    'Frdesmyra',
    'Gjkvassneset',
    'Andotten',
    'Reinykalven',
    'Vassbotndalen',
    'Loppa',
    'Goskamark',
    'Kongsya, Hellya og Skarholmen',
    'Kongsya, Hellya og Skarholmen',
    'Ovdaldasvarri',
    'Roddines',
    'Hjelmsya',
    'Adamsfjord',
    'Vestertana',
    'Tanamunningen',
    'Storgalten',
    'Lille Kamya',
    'Kongsya, Hellya og Skarholmen',
    'Eidvgen',
    'Varangerbotn',
    'Isberglia',
    'Tverrelvdalen',
    'Skoganvarre',
    'Reinya',
    'Ekkerya',
    'Gjesvrstappan',
    'Omgangsstauran',
    'Gapya',
    'Lakselvbukt',
    'Floan',
    'Floan',
    'Srlenangsbotn',
    'Stormyra',
    'Stongodden',
    'Trolldalsvatnet',
    'Dankarvgvatn',
    'Forya',
    'Dyngeneset',
    'Endletvatn',
    'Brannmyra',
    'Skatvikfjellet',
    'Store Follesya',
    'Astujeaggi',
    'Grunnvgvatn',
    'Stormyra (Lapphaugen)',
    'Rakkfjordmyran',
    'Tennvatn',
    'Myrnesset',
    'Spjeltfjelldalen',
    'Altervatn',
    'Jtulhaugvatn',
    'Spkenesra',
    'Kobbevgen',
    'Gravrok',
    'Stormyra (Rossvoll)',
    'Bekkamyra',
    'Fisktjrna',
    'Nordkjosbotn',
    'Blindkjlen',
    'Tiurhaugen',
    'Solhaug',
    'Teksmona',
    'Skardmodalen',
    'Kvannesvatn',
    'Vardnesmyra',
    'Langmyra',
    'Lgmyra',
    'Fauskeeidet',
    'Lomtjnnmyran',
    'Skogvoll',
    'Gimsymyrene',
    'Gimsymyrene',
    'Skogvoll',
    'Votnmyra',
    'Skansenyra',
    'Reppen',
    'Nordbyvatn',
    'Grasmyrskogvatn',
    'Grindysundet',
    'Skognesvgen',
    'Store Tmmervika',
    'Skatvikfjellet',
    'Balteskardvatnet',
    'Sagelvvatn',
    'Gullesfjordbotn',
    'Ringmyra',
    'Svandalen',
    'Mlselvutlpet',
    'Kjlsyvret/Valvr',
    'Skittenskarvholman',
    'Karlsyvr',
    'Kvannlia/Slvjodalen',
    'Javreoaivit',
    'Rykeneselva',
    'Reisautlpet',
    'Hundholmen',
    'Lofotodden',
    'sholman',
    'Borgvret',
    'Hovsflesa',
    'Ulvyvret',
    'Selya',
    'Hongvret/Galtholmen',
    'Frugga',
    'Bleiksya',
    'Anda',
    'St/Nyksund',
    'Gsya/Geitholmen',
    'Floholman',
    'Floholman',
    'Floholman',
    'Sauya',
    'Fuglbergya/Nautya',
    'Ramnholmen',
    'Brunvr',
    'Ljnesya',
    'Nupen',
    'Stttvret',
    'Flatvret/Varkgrd',
    'Otervr',
    'Risvret',
    'Indreholmen/Lyngvret',
    'Lnan/Skjrvr',
    'Nykan',
    'Nykan',
    'Nykan',
    'Engelvr',
    'Kjlsyvret/Valvr',
    'Horsvr',
    'Stubberud',
    'Bjellandsvatnet',
    'Barlindflaten',
    'Ryrtjnn',
    'Dalbo',
    'Triungsvann',
    'Gserumpa',
    'Fokserd',
    'Kisselbergmosen',
    'Korseiksen',
    'Lusemyr',
    'Trollvann',
    'Vinjekilen',
    'Sland',
    'Nesytjern',
    'Selvikvgen',
    'Mslia',
    'Stokkjlen',
    'Horsfjellmyra',
    'rnakken',
    'Skinstadreset',
    'Hendvgen',
    'Fjugstad',
    'Smdalsvatni',
    'Rundeholmen i Opsangervatnet',
    'Frs',
    'Kvanndal',
    'Fluetjern',
    'Sandgrotta',
    'Rosstjern',
    'Tverrdalen',
    'Bjreggene',
    'Svarttjern',
    'Barkeland',
    'Tronstad',
    'Veggermyra',
    'Refsholttjnna',
    'Mrrapanna',
    'Haga',
    'Lyseren',
    'Kulthaug',
    'Blesehelleren',
    'Sellegrod',
    'dnevik',
    'Vestbstadtjrna',
    'Storykilen',
    'Jnjiljo',
    'Brokefjell',
    'Knipheia',
    'Randvik-Store Furuya-Leikerya',
    'Vangestadmyra',
    'Svangtjernmyra',
    'Fossevatna',
    'Viksefjord',
    'Fjosbumyra',
    'Porsmyr',
    'Skarsdalen',
    'Vangdalsberget',
    'Vikaneset',
    'Tau',
    'vre Eide',
    'Sankt Hanssen',
    'Gullkronene',
    'sdalstjrna',
    'Skottjern',
    'Heiavatnet',
    'Heggemyr',
    'Nesvika',
    'Vletjern',
    'Rnnsmyra',
    'Gitlevg',
    'Sandviki',
    'Sjoalemyra',
    'Langevatnet',
    'Krmyrane',
    'Herlandsnesjane',
    'Nats',
    'Joberget',
    'Hillestadsen',
    'Kiletjernene',
    'Burytjern',
    'Elnestangen',
    'Tuemyr',
    'Kolsstoppen',
    'Hgsmsan',
    'Storholmen',
    'Fimreiteholmane',
    'Breimosen',
    'Hustadvassdraget',
    'Grnkjlen',
    'msmyra',
    'Strand',
    'Lomstjnna',
    'Frebergsvik',
    'sjo',
    'Hovstjern',
    'Rundfjelldalselva',
    'Stormyra',
    'Hilmo',
    'Skoland',
    'Gstjrnan',
    'Momyra',
    'Nesheim',
    'Smtjnna',
    'Urvatnet',
    'Skorskog',
    'Bervamyr',
    'stre Ertholmen',
    'Moldfall',
    'Bjrgedalen',
    'Asdljuvet',
    'Kanalen',
    'Vallemsberga og Langya',
    'Ulendeltaet',
    'Fjellmannmyra/Vargdalsfloa',
    'Singsmyra, Svinya',
    'Hindrum',
    'Kanalen',
    'Prestgardselva',
    'Frneidet',
    'Storeidet',
    'Raudya',
    'Fjrtoftneset',
    'Sanddldalen',
    'Seilskjrene',
    'Ulvungene',
    'Dyrysundskjeret',
    'Litle Frilsy, Hovden, Svarteskjeret og Innesyane',
    'Langskjr',
    'Naturreservat sr for Furuholmen',
    'Lagmannsholmen',
    'Litle Frilsy, Hovden, Svarteskjeret og Innesyane',
    'Husvika og Vektarbotn',
    'Hovassdalen',
    'Storsltta',
    'Knarrashaugmyra',
    'Risya',
    'Rognsflauane',
    'Nevlungstranda',
    'Lomundsjmyra',
    'Surna',
    'Surna',
    'yastl',
    'Grimstadvatn',
    'Surna',
    'Surna',
    'Buvika/Rdskjr',
    'Lgendeltaet',
    'Tangvald',
    'Sjmannsheia',
    'Lgsmyr',
    'Ultvedttjern',
    'Skjeftkjlen',
    'Kolssstupene',
    'Nryane',
    'Lomundsjen',
    'Vassgrdsvatnet',
    'Svanvikmyra',
    'Djupvikvatnet-Kringlevatnet',
    'Rotlia',
    'Rndalen',
    'Rndalsmyrene',
    'Mellomkollen',
    'Flakkan',
    'Tverrlimyran',
    'Kjnsyhopen',
    'yenskavlen',
    'Borgan og Frelsy',
    'Borgan og Frelsy',
    'Berglia',
    'Goksyrmyrane',
    'Rauna',
    'Mellemskjr',
    'Fuglyrogn',
    'Terneskjr',
    'Ullebergsen',
    'Mrrapanna',
    'Bjorsund',
    'Krona',
    'Havmyran',
    'Storskjr',
    'Stenerudmyra',
    'Gule-/Stavikmyrane',
    'stensjvann',
    'Stubberud skogpark',
    'Skinnerflo',
    'Hgsen',
    'Hammartjnn',
    'Elnestangen',
    'Store Rekke',
    'Karlshaugen',
    'Sislemyrene',
    'Aurstadmsan',
    'Sakkhusmsan',
    'Smihagen',
    'Oppsjmyrene',
    'Kalvya',
    'Eriksrud',
    'Blessumkalvkveen',
    'Tjrnsmyra',
    'Svarttjernmyra',
    'Evjemyra',
    'Hymyr',
    'Lerdalen',
    'Eggholmen',
    'Langrasta',
    'Bredmosen',
    'Stormyra',
    'Averya',
    'Risheimyi',
    'Hundorp',
    'Langtjedn',
    'Lauvsen',
    'Lundsfjellet',
    'Sagvatnet',
    'Foreknuten',
    'Gitlandssen',
    'krokan',
    'Skland',
    'Langya',
    'Kringlemyr',
    'Drangsdalen',
    'Sndre Missingen',
    'Ilemyr',
    'Jrstadmyra',
    'Ishavet',
    'Spernesmosen',
    'Gulltjernmosen',
    'Tretjernmyra',
    'Venssmyra',
    'Tjnna',
    'Pollen',
    'Eikefjordholmane',
    'Myrbrskjera',
    'Remerhornheiane',
    'Ramyrane',
    'Bakkedalen',
    'Hostadvatnet',
    'Storevik',
    'Lauglolia',
    'Midtskogvatnet',
    'ktmyrene',
    'Krsstjernsen',
    'Skottvatnet',
    'Hgmyran',
    'Dokkadeltaet',
    'Flostranda',
    'Buttekvern',
    'Romsa',
    'Eggja',
    'Ryrtveit',
    'Solevgsfjellet',
    'Skogery-Lyngholmen',
    'Villelia',
    'Mlsjuvet',
    'Sbskra',
    'Mysutjernene',
    'Karlsrudtangen',
    'Lamyra',
    'Juveren',
    'Synneren',
    'Telvanglia',
    'Randvik-Store Furuya-Leikerya',
    'Tuftelia',
    'Randvik-Store Furuya-Leikerya',
    'Farmyrane',
    'Reismyr',
    'Reddalsvann',
    'Kjerkevgen',
    'Grothovdmyran',
    'Augga',
    'Lemostangen',
    'Vinterguten',
    'Strrmyran',
    'Metubba',
    'Sndre Hrtekollen',
    'Kolbergtjernmyra',
    'Sandsbakken',
    'Ren',
    'Bremsa',
    'Gullkronene',
    'Geiterya',
    'Killingholmen',
    'Bumyr',
    'Tveitstulmyr',
    'Lkjin',
    'Humleneset',
    'Lytingsdalen',
    'Hmyrane',
    'Steinevik',
    'Fodnessen',
    'Stenstad',
    'Barlindtjnn',
    'Indre Ulvya',
    'Rekedal',
    'Olashei',
    'Svartefjell',
    'Ulgjelsvann',
    'Ufra',
    'Nesheimvatnet',
    'Granvindeltaet',
    'Vinnesleiro',
    'Hellesjvann',
    'Kollerudvika',
    'Kragtorpvika',
    'Hurdalselvdeltaet',
    'Pollevann',
    'stensjvannet',
    'stensjvannet',
    'Vestre Vansj',
    'Moskjra',
    'Kjennetjern',
    'Skrakilen',
    'Hansemakerkilen',
    'Vestvannet',
    'Storesand',
    'Lysakermoa',
    'Bleiken',
    'Gjlsjen',
    'Hra',
    'Kallakmosen',
    'Vistehorten',
    'Sandehorten',
    'Berdla',
    'Sandbu',
    'Murulonin',
    'Liadalane',
    'Hkster',
    'Norda-Sra',
    'Rolla',
    'Brdsengbekken',
    'Djupdalen',
    'Uri',
    'ytjernet',
    'Igelsrud',
    'Rinilhaugen',
    'Ramberget',
    'Kulpsen',
    'Finnemarka',
    'Tverrbergkastet',
    'Solbergfjellet',
    'Rverkollen',
    'Enghaugberget',
    'Skirvedalen',
    'Heddedalane',
    'Skultrevasssen',
    'Flenten',
    'Haugene',
    'Rismyr',
    'Ertsvikskjr',
    'Rnningsfossene',
    'Lkmyr',
    'Dyna',
    'Dyna',
    'Hamrefjell',
    'Fiskumvannet',
    'Stavlum',
    'Nedre Flyvatn',
    'Braksya',
    'Lemostangen',
    'Lemostangen',
    'Lemostangen',
    'Storya',
    'Purkya',
    'Ullerntangen',
    'Bjoreidalen',
    'Brevika',
    'Floget',
    'Flotaneset',
    'Gullbergnotten',
    'Hestabotn',
    'Hopsfjellet',
    'Kalandsvika',
    'Klyvelia',
    'Kvernavatnet',
    'Lokna',
    'Lnayane',
    'Mannavatn',
    'Otterstadstlen',
    'Rekvesyane',
    'Rimbareidtjrna',
    'Skiftestad',
    'Skogafjellet',
    'Tjeldst',
    'Tveitabotn',
    'Ulvikpollen',
    'Mundheim',
    'Sandtjern',
    'Svenskestutjern',
    'Ljgodttjern',
    'Krokvatnet',
    'Liafjellet',
    'Storsy',
    'Drotninghei',
    'Lunde',
    'Tranmyra',
    'Jvnesmyrane',
    'Vjemyrane',
    'Lindheim-Mannsmyr',
    'Nybutjern',
    'Flottene',
    'Gautefall',
    'Vidmyr',
    'Ryrmyrsen',
    'Bjorvatn',
    'Lekum',
    'Folkedal',
    'Uranes',
    'Eidesvatnet',
    'Vikfjell',
    'Trollhaug',
    'Ambjrndalen',
    'Semsyene',
    'Aksdal',
    'Eiksen',
    'Gjuvastl',
    'Heggheimsfjellet',
    'Vatland',
    'Fisterfjell',
    'rland',
    'Vestedjan',
    'Ajertangen',
    'Eiksen',
    'Hellestveit',
    'Hollastulmyr',
    'Gunnborgdalen',
    'Elva',
    'Stormyr',
    'Brnakollene',
    'Napperdtjern',
    'Robergvannet',
    'Akersvannet',
    'Helakmyrene',
    'Kyrelitjern',
    'Melandsmyrane',
    'Rossmyr og Ospsmyr',
    'Rossmyr og Ospsmyr',
    'Storemyr',
    'Orrhanemyr',
    'Demningane',
    'Berse',
    'Strandvika',
    'Brsesj',
    'Reppadalen',
    'Kjosbukta',
    'Skremyr',
    'Steinsodden',
    'Torster',
    'Kynneggene',
    'Starmoen',
    'Rangklvhammeren',
    'Bergesjen',
    'Torster',
    'Torster',
    'Langmyra',
    'Stenmyra',
    'Hrrenna',
    'Kvannbekken',
    'Klekkefjellet',
    'Furuberget',
    'Maliskjra',
    'Srkilampi',
    'rkjlen',
    'Tufsingdalseskeren',
    'Tufsingdalseskeren',
    'Jutulhogget',
    'Ripan',
    'Seimsjen',
    'Langodden',
    'Svarthaugan',
    'Vesle Rokosjen',
    'Rabali',
    'Foreknuten',
    'Storamyr',
    'Strandnesvgen',
    'Hystad',
    'Iglatjdno',
    'Mlandsdalen',
    'Hildal',
    'Tveitane',
    'Vollom',
    'Fadnesskaret',
    'Blurlia',
    'Blurlia',
    'Stavsholtmyrane',
    'Landtjnn',
    'Rogholt-tjnn',
    'Nordre Skarsholttjnn',
    'Langrudmyra',
    'Tolvmannsmyr',
    'Vle prestegrdsskog',
    'Breimyr',
    'Bergan',
    'Killingholmen',
    'Bjrkya',
    'Tangenbekken',
    'Kjr',
    'Versvik',
    'sstranda',
    'Vassenden',
    'Gausel',
    'Viermyr',
    'Apalviken',
    'Stordamsmyra',
    'Tranemosen',
    'Bensmosen og Berbymosen',
    'Vestre Fuglemosen',
    'Hvitmsan',
    'Vindmyra',
    'Slttmyra',
    'Oppsjmyrene',
    'Oppsjmyrene',
    'Oppsjmyrene',
    'Oppsjmyrene',
    'Knardal',
    'Elnestangen',
    'Spannslokket',
    'Spannslokket',
    'Skotta',
    'Fimreiteholmane',
    'Grnyra',
    'Timberyholmane',
    'Frdspollen',
    'Lihellene',
    'Gsy',
    'Lihellene',
    'Askvika',
    'Flaty',
    'Veststeinen',
    'Refvikvatnet',
    'Fryskjera',
    'Indre-nny',
    'Karsskjeret',
    'Svarteskjeret',
    'Kvannholmen',
    'Presty',
    'Sakrisy',
    'Skor',
    'Vetlefjordsyra',
    'Torsholmane',
    'Kvernyna',
    'Vassyane',
    'Sildekruna',
    'Lysholmen',
    'Stallbrekka',
    'Einevarden',
    'Klovningen',
    'Klovningen',
    'Skorpeholmane',
    'Haukedalsholmane',
    'Haukedalsholmane',
    'Hovdefjell',
    'Rognane',
    'Aralden',
    'Ytteryane',
    'Nekkyta',
    'Nekkyta',
    'Nekkyta',
    'Eikefjordholmane',
    'Eikefjordholmane',
    'Kvalsteinane',
    'Gulholmen',
    'Trefotskjera',
    'Smelvr',
    'Kuyna',
    'Moldvr',
    'Hsteinen',
    'Senholmen',
    'Skardholmen',
    'Kvitingane',
    'Kvitingane',
    'Bunesholmane',
    'Raudy',
    'Krokholmen',
    'Holmelidholmen',
    'naholmane',
    'Ramsholmen',
    'Ramsholmen',
    'Mgyane',
    'Utvr',
    'Indrevr',
    'Oddeholmane',
    'Ramsbarden',
    'Sogneoksen',
    'Sogneoksen',
    'Guleskjeret',
    'Lihellene',
    'Storholmen',
    'Byayra',
    'Espelandsvatnet',
    'Skilbreivatnet',
    'Digernesvatnet',
    'Tungevg',
    'Srdalen',
    'Srdalen',
    'Bargarden',
    'Brandatjrna',
    'Tennyane',
    'Vengane',
    'Flatholmen',
    'Hgfjellet',
    'Rrvikvatnet',
    'Nystervatnet',
    'Lauvsen',
    'Glsvgen',
    'Rdmyra',
    'Hjrungdalsvatnet',
    'Langvatnet',
    'Sandsvgen',
    'Tso',
    'Sanddalstjedn',
    'Jarenvatnet',
    'Vindflomyrene',
    'Puttmyra',
    'Totenvika',
    'Flmyra',
    'Lindstad',
    'Svarverud',
    'Kalstad',
    'Opsahl',
    'Fvang',
    'Krogshavn',
    'Sekkjedalstjrn',
    'Nordstlhei',
    'Ryggsteinen',
    'Gsvr',
    'Svenstad',
    'Tgdalen',
    'Barlindneset',
    'Straumsdalen',
    'Aspsmyran',
    'Raudehaugen',
    'Lyngholman',
    'Helgehornvatnet',
    'Kjerringvatnet',
    'ynadn',
    'Heggemsvatn/Holvatnet',
    'Linborgvatnet',
    'Mossige',
    'Storfloen',
    'Storflotjnna',
    'Lindsmyra',
    'Granholvatnet',
    'Henfallet',
    'Nordelva',
    'Skjerva',
    'Galdalen',
    'Kynndalsmyrene',
    'Olafloen',
    'Grandefjra',
    'Garbergmyra',
    'Rrmyra',
    'Stormyra, Inntian',
    'Sjmyrsen',
    'Hoppardalsmyra',
    'Svorkmyran',
    'Jakopsmyra',
    'Inner Vargfossnesa',
    'Melvasslia',
    'Leira',
    'Grnlia',
    'Litlvatnet',
    'Mormyra',
    'Lunde',
    'Nedre Audna',
    'Hegglandsheia',
    'Fotskarlia',
    'Maursltta',
    'Synesvgen',
    'Molinga',
    'Bjrnmyra',
    'Vinnstormyra',
    'Leinslia',
    'Lyngbudalen',
    'Litlbumyran',
    'Lohnetjnn',
    'Slettestjnna',
    'Kvellandsfossen',
    'Vassland',
    'Hovin',
    'Ytter Skjervollslykkja',
    'Madsya',
    'Helgebostadya',
    'Rstya',
    'Kleveland',
    'Langevann',
    'Orlogskarten',
    'Mandalsheia',
    'Lautjnn',
    'Fiskelandsvatn',
    'Brurehelleren',
    'Instestl',
    'Birkelandsvann',
    'Store ygarden',
    'Lveheia',
    'Grnsltta',
    'Nakkestad',
    'Sognevannet',
    'Bredmyra',
    'Fl-Slipran',
    'Holtvatna',
    'Stormyra',
    'Rauberga',
    'Len',
    'Rnningen',
    'Grnningsbukta',
    'Herdalen',
    'Austdalen',
    'Kjlen',
    'Slendet',
    'Kda',
    'Nesvg',
    'Mrkgonga',
    'Ramstadslottet',
    'Sekken',
    'Vallemsberga og Langya',
    'Storbjrhusdal',
    'Bergssen',
    'Liaberga',
    'Stormyra, rlivatnet',
    'Skraptjnnfloen',
    'Nevra',
    'Strmyra',
    'Barsjen',
    'Bjnnstokkleiva',
    'Rognsmoen',
    'Harestranda',
    'Storskogan',
    'Langnes',
    'Hegramo',
    'Reppesleiret',
    'Flbekksen',
    'Dlaelva',
    'rdalen',
    'Skograubergene',
    'Klingsundet',
    'Okstadmyra',
    'Byhalla',
    'smyra',
    'Lundselvoset',
    'Beingrdsmyra',
    'Bjrgan',
    'Bjrgan',
    'Medjura',
    'ie',
    'Reinbjrmyra',
    'Kaldvassmyra',
    'Sandsra',
    'Sandstad',
    'Sjettenberglia',
    'Hammervatnet',
    'Heggdalslimyran',
    'Kvitmyra',
    'Hattmoenget',
    'Stallvikmyran',
    'Stormyra',
    'Grytbogen-Kubsen',
    'Langdalen',
    'Himmelriket',
    'Gartlandselva',
    'Flenga',
    'Solem',
    'Litlstelva',
    'Gaupdalen',
    'Hissen',
    'Seljebotsmyrane',
    'Storslettkjlen',
    'Gjelamyra',
    'Sandvikmyrane',
    'Einsetmyra',
    'Glorvikmyra',
    'Langskjrene',
    'Gjesssjen',
    'Store Mkholmen',
    'Litle Gsy, Skarvy og Store Lambholmen',
    'Nordstre Askeskjr',
    'Sandholmen',
    'Ytre Vassholmen',
    'Ulykkesskjr',
    'Hvalskjret',
    'Svennesvollene',
    'Vestre Skjret',
    'Lagmannskjr',
    'Kavringen',
    'Lge Islendingen',
    'Eggholmen',
    'Terneholmen og Grnningen',
    'Litle Gsy, Skarvy og Store Lambholmen',
    'Hellisy',
    'Omborsnesholmane',
    'Lny',
    'Terneholmen',
    'Prinseskjr',
    'Mkkalassene',
    'Teistholmen',
    'Lindholmane',
    'Prestnesholmen',
    'Sandholmane, ysteinen og Hesjet',
    'Sundbyholmene',
    'Dyna',
    'Lindholmane',
    'Lille Sstein',
    'Selskjra',
    'Rognholmen',
    'Buyskjra',
    'Ruholmen',
    'Kortknappskjer og Horsy',
    'Lindalen',
    'Utslettey, Joy og Upsykalven',
    'Hovsy, Ltersy, Melne, Melneklubben, Lyngsy, Oksy og Raudholmane',
    'Hovsy, Ltersy, Melne, Melneklubben, Lyngsy, Oksy og Raudholmane',
    'Notholmen',
    'Lurekalven',
    'Vestre og Indre Mgabl, Myrbrholmen og Kvitingen',
    'Mksteinane',
    'Laksholmen',
    'Olvondo',
    'Karihavet',
    'Senjen',
    'Vgsholmen, Gulaskjer, Brattholmen og Grasholmen',
    'Vgsholmen, Gulaskjer, Brattholmen og Grasholmen',
    'Rauny, Langy, Skardholmen, Storholmen og Hgholmen',
    'Fluyane med Fluyskjeret, Lyngy, Veesyane og Terneskjeret',
    'Vgsholmen, Gulaskjer, Brattholmen og Grasholmen',
    'Rauny, Langy, Skardholmen, Storholmen og Hgholmen',
    'Fluyane med Fluyskjeret, Lyngy, Veesyane og Terneskjeret',
    'Guleholmane',
    'Bleikenvlingen og Hgskjeret',
    'Bleikenvlingen og Hgskjeret',
    'Kortknappskjer og Horsy',
    'Rrvikholmene',
    'Stakketoskjret',
    'Storskjret',
    'Lille Halsholmen',
    'Ruholmen',
    'Lille Lestholmen',
    'Mannskjret',
    'Stangholmen',
    'Gseholmen og Slettholmen',
    'Brattholmene',
    'Lyngholmen',
    'Hellyholmen',
    'Hellesunds-Grnningen',
    'Gseholmen og Slettholmen',
    'Breivigskjret',
    'Sundholmen',
    'Malmen',
    'Kongsholmen',
    'Lille-Danmark',
    'Olavskjran',
    'Hummerholmen',
    'Agneskjret',
    'Aksnesholmane',
    'Aksnesholmane',
    'Kjeholmskjra',
    'Bukkholmskjra',
    'Hillekalven og Pasholmen',
    'Hillekalven og Pasholmen',
    'Hovsy, Ltersy, Melne, Melneklubben, Lyngsy, Oksy og Raudholmane',
    'Hovsy, Ltersy, Melne, Melneklubben, Lyngsy, Oksy og Raudholmane',
    'Hovsy, Ltersy, Melne, Melneklubben, Lyngsy, Oksy og Raudholmane',
    'Hovsy, Ltersy, Melne, Melneklubben, Lyngsy, Oksy og Raudholmane',
    'Hovsy, Ltersy, Melne, Melneklubben, Lyngsy, Oksy og Raudholmane',
    'Sengane',
    'Utslettey, Joy og Upsykalven',
    'Utslettey, Joy og Upsykalven',
    'Trttebleikja',
    'Eggvr',
    'Skno',
    'Fluyane med Fluyskjeret, Lyngy, Veesyane og Terneskjeret',
    'Fluyane med Fluyskjeret, Lyngy, Veesyane og Terneskjeret',
    'Fluyane med Fluyskjeret, Lyngy, Veesyane og Terneskjeret',
    'Fluyane med Fluyskjeret, Lyngy, Veesyane og Terneskjeret',
    'Steglholmen og Gseskjer',
    'Steglholmen og Gseskjer',
    'Sandholmane',
    'Raudholmane',
    'Kubbholmen',
    'Vgsholmen, Gulaskjer, Brattholmen og Grasholmen',
    'Perholmen',
    'Ringaskjer',
    'Furuholmen',
    'Terneholmen',
    'Jakobsholmen, Lilleholmen og Rundholmen',
    'Ottery og Hestholmen',
    'Ottery og Hestholmen',
    'Illholmane',
    'Fjraskjer',
    'Raudholmane',
    'Brattholmen',
    'Terneskjeret',
    'Trollskjeret',
    'Bleikjo',
    'Tangbleikjo',
    'Koly',
    'Hjartholmen',
    'Terneskjeret (Austevoll)',
    'Mkstra-Grningana',
    'Vestre og Indre Mgabl, Myrbrholmen og Kvitingen',
    'Vestre og Indre Mgabl, Myrbrholmen og Kvitingen',
    'Selyskjera',
    'Litle Gsy, Skarvy og Store Lambholmen',
    'Trytarosskjeret',
    'Mksteinen og Tovo',
    'Illholmane',
    'Krko',
    'Hanyklubben',
    'Ertenya',
    'Greipingen',
    'Ullebroten',
    'Klammersholmen',
    'Lodd',
    'Stridsholmen',
    'Vgsskjeret',
    'Grningane',
    'dny',
    'Rauny, Langy, Skardholmen, Storholmen og Hgholmen',
    'Rauny, Langy, Skardholmen, Storholmen og Hgholmen',
    'Hery',
    'Sandholmane, ysteinen og Hesjet',
    'Synny',
    'Hvarden og Klubben',
    'Kattholmane',
    'Krka',
    'Lindholmane',
    'Torskholmen',
    'Geitholmsundet',
    'Kvitskjrene',
    'Knerten',
    'Lille Bjerkyskjr',
    'Svartskjra',
    'Hvarden og Klubben',
    'Smskjran',
    'vre og Nedre Svinholmen',
    'vre og Nedre Svinholmen',
    'Udvre',
    'Skjede',
    'Klovholmene',
    'Bjrnen',
    'Skotholmen',
    'Kjorten',
    'Marky',
    'Revsund',
    'Sandgjelet',
    'Rotnedalen',
    'Knebeknuten',
    'Dyrlimyra',
    'Krokkleiva',
    'Oppkuven - Smeddalen',
    'Sandblst/Gaustadvgen',
    'Borrevannet',
    'Hiesten',
    'Osdalssjhgda',
    'Stimannsberget',
    'Klvstadhgda',
    'Rnnomdalen',
    'Steinvika',
    'Einarvannet',
    'Skrstadheia',
    'Grttingnea',
    'stmarka',
    'Sndre Hya',
    'Haraldsfjellet',
    'Vardmoan',
    'Ulvkjlen',
    'Tufsingdeltaet',
    'Endelausmyrene',
    'Osdalen',
    'Lille Slensj',
    'Nekmyrene',
    'Grimsmoen',
    'Longavatnet',
    'Frekmyr',
    'Galtsjen',
    'Rtkjlen',
    'Hesjemarka',
    'Lavsjmyrene-Mlikjlen',
    'Tanarkjlen',
    'Hukkelvatna',
    'Skjelldalen',
    'Ryklibotnet',
    'Lille Korssjen',
    'Hanestadnea',
    'Middagskollen',
    'Jordstyp',
    'Korpen',
    'Vemannss',
    'Rysa',
    'sermarka',
    'Sletner',
    'Gullenhaugen',
    'Skotjernfjellet',
    'Solfjellsene',
    'Strykensen',
    'Gullerudtjern',
    'Ramfoss',
    'Branden',
    'Sandvikbotn',
    'Langesundstangen',
    'Grnehaugen',
    'Kongsrudtjern',
    'Bremssen',
    'Stavnselva',
    'Grvelsjen',
    'Osen',
    'Vigre',
    'Amdam',
    'Amdam',
    'Rolsya',
    'Horta',
    'Horta',
    'Horta',
    'Sklinna',
    'Fruflesa',
    'Kjeya',
    'Nordyan',
    'Nordyan',
    'Sryan',
    'Sryan',
    'Steinan og Flottra',
    'Aldgrden',
    'Steinan og Flottra',
    'Rambergholmen',
    'Hoya',
    'Kolebakkane',
    'Hkybotn',
    'Hornya og Reinya',
    'Kvaly og Rauy',
    'Kvaly og Rauy',
    'Bjrklund',
    'Kloppemyrane',
    'Lona',
    'Kleppsstlsvatnet',
    'Dekkjene',
    'Yngsdalen',
    'Eikevolltjnnmyra',
    'Gjerlandsyane',
    'Grima',
    'Svartelismyra',
    'Storemyra',
    'Tvinna',
    'Prestestylen',
    'Myklebustdalen',
    'Sandvikseidet',
    'Tjnnane',
    'Srebmyrane',
    'Movatna',
    'Stremyrane',
    'Tuemyra',
    'Leirpollen-Halsvatnet',
    'Sandbukta',
    'Sandsvika',
    'Skibotnutlpet',
    'Lekangsya',
    'Sundsvollsundet',
    'Froholman',
    'Leirpollen-Halsvatnet',
    'Spilderya',
    'Forya',
    'Sandbukta',
    'Auvr',
    'Gapyholman',
    'Hakstein',
    'Hakstein',
    'Bjormyr',
    'Rullestadtjern',
    'Midtsjvann',
    'Nrevann',
    'Melland',
    'Farstadbukta',
    'Korsbrekke',
    'Ristesundsanden',
    'Molnes',
    'Solnrvika',
    'Tresfjorden',
    'Rstadtangen',
    'Hjertvika',
    'Langyvgen',
    'Osen',
    'Oltervgen',
    'Batnfjordsra',
    'Hgsetleira',
    'Todalsran',
    'Reitvgen',
    'Mellandsvgen',
    'Hensran',
    'Nauste',
    'Sysetran',
    'Hustadbukta',
    'Latharimoen',
    'Nord-Talgje',
    'Msra-Hofstadra',
    'Slevdalsvann',
    'Langebudalen',
    'Hovsfjorden',
    'Vally',
    'Kjellingen',
    'Kjellingen',
    'Skjringen',
    'Songvaar, Hellersya og Kubbya',
    'Slettingen',
    'Kjellingen',
    'Sndre Eggvr',
    'Oks',
    'Vally',
    'Herya',
    'Store Vengelsholmen',
    'Songvaar, Hellersya og Kubbya',
    'Herya',
    'Store Lyngholmen',
    'Imsdalen',
    'Koloberget',
    'Saltstutlia',
    'Skardseterlia',
    'Barmen',
    'Tekssjen',
    'Bymarka',
    'Djupa og Grtshaugen',
    'Bjnntjenn',
    'Lauvhgdi',
    'Mlslia',
    'Vamsen',
    'Setningen',
    'Bjrkodden',
    'Volaberget og Kvemskjlen',
    'Gransen',
    'Kvernlia',
    'Storberget',
    'Kvisleflet og Hovdlia',
    'Smoldalen',
    'Svartsfjellet',
    'Tronkberget',
    'Stors',
    'Lunnane',
    'Dokkene',
    'Presteseter',
    'Storskog',
    'Svingervann',
    'Bjugnholmen',
    'Bjugnholmen',
    'Buholman',
    'Melstein',
    'Myan',
    'Solya',
    'Svesya',
    'Begna',
    'Tofteskogen',
    'Luster Allmenning',
    'Bratts',
    'Storsteinfjell',
    'Skottfjell',
    'Steinknapp',
    'Risdalen',
    'Materialen',
    'Solhomfjell',
    'Ramssen',
    'Vestre Hovedya',
    'stre Hovedya',
    'Berkneset',
    'Kvamsetelva',
    'Alstranda',
    'Raudnesvika',
    'Gjevenesstranda',
    'Ottem',
    'Smvollen',
    'Todalssetra',
    'Kallset',
    'Sjholt',
    'Havgane',
    'Sulesund',
    'Grytahatlen',
    'Myskjaurene',
    'Skorgeura',
    'Mjlvabotnen',
    'Unjemslia',
    'Tjuvholmen/Klumpholmen',
    'Lindy, Tednholmen og Slttholmen',
    'Tjuvholmen/Klumpholmen',
    'Aatholmane (m.fl.)',
    'Vollholmen',
    'Tde',
    'Nordre Longaskjer',
    'Vestre Mjlsnesholmen',
    'Kattholmen',
    'Indrevr',
    'Tednholmen',
    'Nauty, Longholmen og Bukkholmen',
    'Tingelste',
    'Svholmane',
    'Oppsalholmen',
    'Norheimsy og Lamholmen',
    'Grasholmen og Knibringen',
    'Langholmen, Larsholmen og Larsholmskjeret',
    'Kjey',
    'Hovda Grasholmen',
    'Kyrkjeskjeret',
    'Reilstad - Grasholmen',
    'Brennevinsskjeret',
    'Jarstein',
    'Ferkingstadyene',
    'Spannholmane',
    'Ryvingen og Klovningen',
    'Jegningen',
    'Gittery',
    'Skreholmen',
    'Gsholmen og rvikholmen',
    'Horgje',
    'Tedneholmen',
    'Lauvikholmen',
    'Litle Mary',
    'Srensholmen',
    'Aatholmane (m.fl.)',
    'Aatholmane (m.fl.)',
    'Store og Litle Fokksteinen',
    'Hagset',
    'Boksaspa',
    'Gylhamran',
    'Knutsliya',
    'Oppdlsstranda',
    'Brskjalia',
    'Svorkalia',
    'Raudsandberget',
    'Storkollen',
    'byelva',
    'Gjermundsholmen',
    'Brattykollen',
    'Valberg',
    'Srsjen',
    'Eldedalen',
    'Eldedalen',
    'Eldedalen',
    'Karnes',
    'Karnes',
    'Karnes',
    'Sotnakkvatnet',
    'Kolknuten',
    'Flensmarka',
    'Stensdalen',
    'Juveruddalen',
    'Hydalmoan',
    'Solumsmoen',
    'vermoen',
    'Fiskumfoss',
    'Grenimsan',
    'Sndre Verksya',
    'Ranvikholmen',
    'Grya',
    'Holtnesdalen',
    'Smdaladn',
    'Murefjell',
    'Torjusheia',
    'Urdalen',
    'Vereknutane',
    'Tretjerna',
    'Gardfesthaugen-Gravsen',
    'Lysen',
    'Slseterlia',
    'Svendalen',
    'Hovdsjmyrene',
    'Hemmeldalen',
    'Rangeldalen',
    'Sankkjlen',
    'Geitaknottene',
    'Geitaknottene',
    'Yddal',
    'Rsskleiva',
    'Nustad',
    'Varaldsy',
    'Nesheimvann',
    'Store Sametti - Skjelvatnet',
    'Risya',
    'Sandbukta-stnestangen',
    'Holmedalsberget',
    'Srestrandvatnet',
    'Kjlvikskorpa',
    'Urter',
    'Bjargavatnet',
    'Eptavatnet',
    'Frsvollvatna',
    'Grannesbukta',
    'Grunningen',
    'Hagavgen',
    'Harvalandsvatnet',
    'Hauskjevatnet',
    'Heigremyra',
    'Kydlesvatnet',
    'Landavatnet',
    'Landavatnet',
    'Lindevollsmyra',
    'Linemyra',
    'Lonavatnet',
    'Lundarsyla',
    'Ragstjrna',
    'Smokkevatnet',
    'Sylandsvatnet',
    'Tjsvollvatnet',
    'Tornesvatnet',
    'Vasshusvika',
    'ksnevadtjnn',
    'Alvevatnet',
    'rstad',
    'Dikeelva',
    'Nordskogen',
    'Jomsknutene',
    'Haugsjknipen',
    'Gulspettvannet',
    'Hlvannet',
    'Bersvenmyra',
    'Skjellingshovde',
    'Leirfalla',
    'Nordre yeren',
    'Delingsdalen',
    'Rsok',
    'Srumsneset',
    'Vlberget',
    'Skorbekklia',
    'Holmdalen',
    'Landfallvika',
    'Midtibrenna',
    'Munklia',
    'Munklia',
    'Stange',
    'Trillemarka-Rollagsfjell',
    'Elvsen',
    'Lokbekken',
    'Dragsen',
    'Dragsvollan',
    'bakkfjellet',
    'Vetafjellet',
    'Vestre Lukashaugen og Bornoberget',
    'Marifjell',
    'Slattumsra',
    'Fjellsjkampen',
    'Tostenelva',
    'Mlmannsdalslia',
    'Orrevatnet',
    'Grningane',
    'Bjrvatnet',
    'Kaninya',
    'Nordre Malmya',
    'Bjerks',
    'Heggholmen',
    'Ekebergskrningen',
    'Sndre Skjlholmen',
    'Gsya',
    'Geitholmen',
    'Langra',
    'Langra',
    'Borya',
    'Lilleya',
    'Syd Oust',
    'Store Herbern',
    'Skogerholmen',
    'Kjeholmen',
    'Borya',
    'Borya',
    'Borya',
    'Borya',
    'Gsya',
    'Bleikya',
    'Ekebergskrningen',
    'Ildjernet',
    'Danmark',
    'Gressholmen-Rambergya',
    'Stormyrlia',
    'Kyrhaugvatna',
    'Remman',
    'Hopavassdraget',
    'Aunvgen',
    'Sjvgen',
    'Sortna',
    'Fltjnna',
    'Nordre Pollen',
    'Kleppefjell',
    'Nord-Fuglya',
    'Breivika',
    'Srfuglya',
    'Flatvr',
    'Flatvr',
    'Kvitvr',
    'Msvr',
    'Geitungsholmen',
    'Tofteholmen',
    'Mlen',
    'Veals',
    'Grunnane',
    'Skrfjellet',
    'Steinosen/Sjmyrpollen',
    'Steinslandsosen',
    'Brennvika',
    'Lian',
    'Holmholmen',
    'Vallabotn, Breivika og Rssauren',
    'Vallabotn, Breivika og Rssauren',
    'Vallabotn, Breivika og Rssauren',
    'Skeilia',
    'Laksgaosen',
    'Storhaugen',
    'Tjeldneset',
    'Teisdalen',
    'Strengivatnet',
    'Hammer',
    'Sundsbukta',
    'Lovunda/Lundeura',
    'Solbergheia',
    'Kvenntjnnane',
    'Vigla',
    'Finnfloen',
    'Litlrien',
    'Djuptjnna',
    'Tjerryan',
    'Alv',
    'Torvya og Bjerkholmen',
    'Nordre Skjlholmen',
    'Nordre Skjlholmen',
    'Nordre Skjlholmen',
    'Langskjr',
    'Koksabukta',
    'Fjellheia',
    'Bjellandshaugane',
    'Jurdalsknuten',
    'Myklandsvatna',
    'Glupen',
    'Midtstrondbekken',
    'Mlslia nord',
    'verland',
    'Sndre Sletter',
    'Vesle Sletter',
    'Eldya',
    'Kvinnafossen',
    'Loi',
    'Rnset',
    'Stedjeberget',
    'Ytamo',
    'Eiterstrondi',
    'Lindvik',
    'sane',
    'Haukvatnet',
    'Mallasvika',
    'Steiehalsen',
    'Rnset',
    'Mjta',
    'Husum',
    'Paulen',
    'Hemskilen',
    'Veals',
    'Dalasen',
    'Flisefyr-Hidalen',
    'Hells',
    'Totensen',
    'Klokken',
    'Brdalen',
    'Sulustaddalen',
    'Skydskjr',
    'Stormyra',
    'Simle',
    'Grsss',
    'Presteheie',
    'Aure',
    'Presten',
    'Dale',
    'Nry prestegrd',
    'Fosnes prestegrd',
    'Olaengsen',
    'Spillumsbekken',
    'Skogkjerringholet',
    'Fjelldalslia',
    'Veggen',
    'Hitterdbekken',
    'Eggholmane-Lisjeholmen',
    'Skalmen',
    'Eidsholmen',
    'Grip',
    'Orskjera',
    'Fuglya',
    'Tromskjera-Mannskjera',
    'Bfjordholmane',
    'Saltstein-Klvningen',
    'Rssholmen-Skjela-Oterholmen',
    'Orholmen-Grningen',
    'Sveltingen',
    'Prestholmen',
    'Svetlingane',
    'Vistdalsholmen',
    'Husfjellet',
    'Tautra, vest',
    'Storholmen',
    'Rdholmen',
    'Feya',
    'Msehamrane',
    'Langholmen',
    'Erkna',
    'Gjsundholmen',
    'Stredalen',
    'Kjepina',
    'Vegsundholmane-Veibustholmen',
    'Eggholmen',
    'Muleneset',
    'Svinya',
    'Riste',
    'Nupafjellet',
    'Vindfarholmen',
    'Flrauden',
    'Sandya-Vattya',
    'Mze',
    'Bruvollhagan',
    'Bruvollhagan',
    'Froan',
    'Mariafjellet',
    'Flokoa',
    'Skiftenes',
    'Mrkvassjuvet',
    'Mrkvassjuvet',
    'Asgjerdstigfjellet',
    'ra',
    'Refsnes',
    'Vardsen',
    'Kurefjorden',
    'Remmendalen',
    'Skjlysundet',
    'Krkery-skjrgrden',
    'Kongshavntjern',
    'LangfjelldalenHolmdalen',
    'Lrensetertjern',
    'Karusspytten',
    'Rbesdalen',
    'Engevik',
    'Haramsya vestside',
    'Vesteinvika',
    'Eventyrskogen',
    'Eljestraum',
    'Tveitvann',
    'Styggedalen',
    'Kariholet',
    'Ravndalen',
    'Nannestad kapellangrd',
    'Hevillen',
    'Hevillen',
    'Hevillen',
    'Hevillen',
    'Hevillen',
    'Hevillen',
    'Hevillen',
    'Hevillen',
    'Aundalen',
    'rnesbukta',
    'Jan Mayen',
    'Storvatnet',
    'Varnvassdalen',
    'Storslettmyra',
    'Oddan',
    'Rssjen',
    'Hersjmyrin',
    'Oppsjmyra',
    'Skardberga',
    'Kjlane',
    'Hynna',
    'Rossefjellet',
    'Sandfjordneset',
    'Syltefjorddalen',
    'Syltefjorddalen',
    'Ytre Syltevika',
    'Hydalsfjellet',
    'Rivingen',
    'Gausdalen',
    'Linnesstranda',
    'Linnesstranda',
    'Fladalssen',
    'Hestebrennajuvet',
    'Kollsen',
    'Hostegga',
    'Rottsberga',
    'Finntjnnin',
    'Rkkesdalen-Skogndalen',
    'Klrtjnnhaugen',
    'Sunndalslia',
    'Mjsund',
    'Tverra',
    'Almdalen-Ekorndalen',
    'Bangsjan',
    'Jamtheimen',
    'Bangsjan',
    'Breivatnet',
    'Rinnleiret',
    'Ausvasstormyra',
    'Simadalen',
    'Hgmannen',
    'Koltjnndalen',
    'Fregn',
    'Hengssen',
    'Dronningberget',
    'Grudevatn',
    'Herdla',
    'Einunndalsranden',
    'Bjrndalen',
    'Midt-Smla',
    'Sveli',
    'Gjellebekkmyrene',
    'Jerna',
    'Lava',
    'Gita',
    'Torsterkampen',
    'Dokka',
    'Saga',
    'Selsjen',
    'Helvete',
    'Fjluelva',
    'Lone',
    'Ledsageren',
    'Knlltjenna',
    'Storfelten',
    'Midtfjellmosen',
    'Kjrholmane',
    'Lurkevann',
    'Tjstl',
    'Lundsneset',
    'Fuglemosehgda',
    'Haugbergfjellet',
    'Gaupesteinmarka',
    'Mrkeli',
    'Myklebustvatnet',
    'Tautra',
    'Tautra',
    'ksningen',
    'Straumen',
    'Listeid',
    'Hgkjlen/Bakkjlen',
    'Norddalen',
    'Fuglevasslia',
    'Ands',
    'Nordre Brynsa',
    'Ytre Lauvrak',
    'Fjella',
    'Strnes',
    'Kvannskogen',
    'Drevdalen',
    'Drevdalen',
    'Atnoset',
    'Atnoset',
    'Atnoset',
    'Kalvmyra',
    'Mikkelsberget',
    'Hanestadvola',
    'Ytterya',
    'Eidsfjellet',
    'Lftlia',
    'Lftlia',
    'Brenslefjellet',
    'Jerndalsfjellet',
    'Askevann',
    'Sand og Henestangen',
    'Gukilhgda',
    'Fuglen og myr',
    'Prestebakkefjella',
    'Veikulsen',
    'Grnknuten',
    'Halvfarsen',
    'Askerudbekken',
    'Hgtidssen og Svartfjellet',
    'Mastedalen',
    'Snstebybekken',
    'Sandungsen',
    'Mjvann',
    'yvassheia',
    'mtona',
    'Heltveit-Bjrge',
    'Henrikstjnna',
    'Renlia',
    'Splen-Katnosa',
    'Odnesberga',
    'snes',
    'Hammeren',
    'Fugldalen',
    'Presterdkilen',
    'Nlbogen',
    'Samsjen',
    'Grntjnnan',
    'Skaumsjen',
    'Henddalen',
    'Ledalen',
    'Bgmyra',
    'Hellheia',
    'Store Svartya',
    'Bliksvr',
    'Bliksvr',
    'Bliksvr',
    'Bliksvr',
    'Bliksvr',
    'Bliksvr',
    'Bliksvr',
    'Bliksvr',
    'Bjortjnnlimyrene',
    'Langtjrnlia',
    'Straume',
    'Grunnfjorden',
    'Elsfjorden',
    'Osen/Sandvret',
    'Kjerkvatnet',
    'Naut',
    'Kjellerhaugvatnet',
    'Holandsosen',
    'Eidemsliene',
    'degrden',
    'Rubbelifjell',
    'Grneliane',
    'Tegningdalen',
    'Trautskogen',
    'Brumundsjen-Harasjmyra',
    'Vlerberget',
    'Holmby',
    'Hakaskallen',
    'Mrka',
    'Viengskletten',
    'Bergevika',
    'Bergevika',
    'Sndre Versvik',
    'Grytdalen',
    'Orsjmyra',
    'Flaaten',
    'Elferdalen',
    'Persholknatten',
    'Linddalsliane',
    'Svarverudelva',
    'Glitra',
    'Fuglya',
    'Grunnvatnet',
    'Herringbotn',
    'ykjeheia',
    'ykjeheia',
    'Virvassdalen',
    'Fiskvgflget',
    'Feren',
    'Feren',
    'Gudfjellya/Tjehkere',
    'Gudfjellya/Tjehkere',
    'Merkesfloen',
    'Muusdalan',
    'vre Forra',
    'Grnningen',
    'Tjrvgosen',
    'Vestfjorddalen',
    'Engasjyen',
    'Haverstingen',
    'Hisdalen',
    'Mardalen',
    'Mardalen',
    'Haukskardmyrin',
    'Kattuglehi',
    'Veslehjerkinntjnnin',
    'Flakkstjnna',
    'Grimsdalsmyrene',
    'Hjerkinnholen',
    'Vermedalen',
    'Nordre Snfjelltjrn',
    'Fokstumyra',
    'Myldingi',
    'Atnsjmyrene',
    'Flman',
    'Melyfloen',
    'Stakkengfonna',
    'Muldalslia',
    'Slettsvaet',
    'Mestermyre',
    'Brettingsmoen',
    'Einstullie',
    'Eikebakka',
    'Tveitaneset',
    'Urddalen',
    'Elgsjen',
    'Hildremsvatnet',
    'Grytdalen',
    'Kvasshyllan',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'nuglo, Midtya, Selya og Flornes',
    'Hattersen',
    'Kols',
    'Samsjberga',
    'Moldberget',
    'Liaberget',
    'Kile',
    'Ulbergsa',
    'Sula',
    'Falken',
    'Svartdalstjerna',
    'Oddelia',
    'Bjrhusnatten',
    'Sjforsen',
    'Alterhaug',
    'Hammarnesflget',
    'Sknland',
    'Fiskosura',
    'Drevjaleira',
    'Fiskvgvatnet',
    'Kjeggen',
    'Nystadneslia',
    'Sundstraumlian',
    'Steinslandsvatnet',
    'Ytre Klungset',
    'Veten',
    'Straumya',
    'Loddvatnet',
    'Seinesodden',
    'Tverlandet',
    'Urskar',
    'Sagvassdalen',
    'Smvatnan',
    'Enga',
    'verengmoen',
    'Glitrelia',
    'Blfjell',
    'Rudskampen',
    'Prekestolen',
    'Gardlaushgda',
    'Snellingsrysene',
    'Lillomarka',
    'Djupdalen og Kjaglidalen',
    'Trollmyr',
    'Ringisen',
    'Mstadfjellet',
    'Leirvika',
    'Hopvasslia',
    'Gardsjen',
    'Vhcanjohka',
    'Veikdalen',
    'Husbymarka',
    'Dillern/rnes',
    'Blakkdalen',
    'Semska-Stdi',
    'Storlia',
    'Dypen',
    'Stor-Graddis',
    'Junkerdalsura',
    'Mannfjordbotn',
    'Henneseidfjellet',
    'Godfjordbotn',
    'Paradisbukta',
    'Nakholmen',
    'Nakholmen',
    'Nakholmen',
    'Nakholmen',
    'Nakholmen',
    'Lindya',
    'Fjre',
    'Langskjlen',
    'Skjebergkilen',
    'Kvernemyr',
    'Haugetjern',
    'Tiltvika',
    'Esvikhatten',
    'Ostjnna',
    'Vardya',
    'Salvatnet',
    'Sklsvikleira/Ystleira',
    'sen - Kjeldalen',
    'Brsvatnet',
    'Selnesvatnet',
    'Kinnhalvya',
    'Kommersya',
    'Kommersya',
    'Pirane',
    'Ringane',
    'Mulsen',
    'Lvya',
    'Malmya',
    'Hummerbakken',
    'Adalstjern',
    'Askvikmyra',
    'Bliksekilen',
    'Bogen',
    'Falkensten',
    'Raudvasssen',
    'Fisklausvatnet',
    'Simskarmyra',
    'Skjelstad',
    'Gammelelva',
    'Murudalen',
    'Vassholmen',
    'Gjerdevatnet',
    'Amundsgjerdlia',
    'Bpla',
    'Prestegrdskogen',
    'Prestegrdskogen',
    'Bihkkacohkka',
    'Korsfjorden',
    'Leirbotndalen',
    'Simaklubben',
    'Brselvdalen',
    'Gojohka',
    'Oahcesaisuolo',
    'Langfjorddalen/Laggu',
    'Oksevgdalen',
    'Torskefjorddalen',
    'Trollfjorddalen/Gulgo',
    'Hanadalen',
    'Harrelv',
    'Julelvdalen',
    'Svartbotn',
    'Nordsandfjorden',
    'Srsandfjorden',
    'Svrholtklubben',
    'Kinaroddsandfjorden',
    'Hurumsen/Burudsen',
    'Neiden- og Munkefjord',
    'Skrim og Sauheradfjella',
    'Skrim og Sauheradfjella',
    'Skrim og Sauheradfjella',
    'Trillingtjennane',
    'Burmannsfjellet',
    'Omnflug',
    'Eikelifjellet',
    'Minnesj',
    'Trolldalsfjellet',
    'Stuttgonglie',
    'Veogjelet',
    'Ridderspranget',
    'Baklie',
    'Knipetjennsen',
    'Fossetersen',
    'Fossetersen',
    'Fossetersen',
    'Fossetersen',
    'Juvssen',
    'Saksfjorden',
    'Barvikmyran og Blodskytodden',
    'Vkker/Vkkr',
    'Sanden',
    'Slettnes',
    'Storelvosen',
    'Brselvosen',
    'Stabbursnes',
    'Djupvika',
    'Makkaurhalvya',
    'Nesseby',
    'Geislafoss',
    'Geislafoss',
    'Geislafoss',
    'Geislafoss',
    'Hgbostad',
    'Mytlaskardet',
    'Ramss',
    'Mytla',
    'Kjesbu - Hgmannen',
    'Gravhaugen',
    'Buvika',
    'Ldding',
    'Kvamsfjellet',
    'Kvamsfjellet',
    'Guselva',
    'Storgaulstadhgda-Trollfossklompen',
    'Storgaulstadhgda-Trollfossklompen',
    'Arvasslia',
    'Berglimyra og Klumplifjellet',
    'Gaundalsmyra',
    'Guslia',
    'Storfloa',
    'Finnvolldalen-Esplingdalen',
    'Migaren',
    'Holden',
    'Solbrlia',
    'Langvassbrenna',
    'Jukulen',
    'Rokka',
    'Bjellneset',
    'Bjellneset',
    'Bjellneset',
    'Slttbrtmyra',
    'Juvberget',
    'Elda',
    'Misterlia',
    'Veslhammarlia',
    'Fuggdalen',
    'Steinfjellet',
    'Hvaler prestegrdskog',
    'Hvaler prestegrdskog',
    'Svartmoen',
    'Gjrahaugen',
    'Minilldalsmyrene',
    'Svartmoen',
    'Raknerud og Gimmingsrud',
    'Urdvatn og Kallingshei',
    'Urdvatn og Kallingshei',
    'Urdvatn og Kallingshei',
    'Urdvatn og Kallingshei',
    'Urdvatn og Kallingshei',
    'Eikelidalen',
    'Rislknuten',
    'Langebergsheia og Mannfallknuten',
    'Eiksen',
    'Stuvna',
    'Berlifjell',
    'Badstudalen',
    'Gjerimsan',
    'Prestehesten',
    'Lgen',
    'Lavangselva',
    'Lislevatn',
    'Lykkjevatn',
    'Migaren',
    'Vidmyr',
    'rest',
    'Hisdal',
    'Ljosdalen',
    'Vestfjella',
    'Spirodden',
    'Lkenesskogen',
    'Grandalssen',
    'Vindfjell',
    'Fimreitesen',
    'Fimreitesen',
    'Granslia',
    'Askilssen',
    'Lunde',
    'Ryggssen',
    'Brvatnet',
    'Thorsma',
    'Tangen',
    'Rambergbukta',
    'Gullholmen',
    'Kajalunden',
    'holmen',
    'Bleikmorenen',
    'Slemmestadsen - Morberg',
    'Slemmestadsen - Morberg',
    'kersvika',
    'kersvika',
    'kersvika',
    'kersvika',
    'kersvika',
    'kersvika',
    'Fuglevikbukta',
    'Sandysalta',
    'Holmen',
    'Jlsen',
    'Stilla og Brauterstilla',
    'Stilla og Brauterstilla',
    'Trollpollen',
    'Eggum',
    'Tangvolla',
    'Homla',
    'Blekebakken',
    'Frierflogene',
    'Laukvikyene',
    'Lilandsvatnet',
    'Arstadlia - Tverrviknakkan',
    'Arstadlia - Tverrviknakkan',
    'Stavnes',
    'Stavnes',
    'Langvassdalen-Ruffedalen',
    'Vardeheia',
    'Geiteryggmyra',
    'Storberget',
    'Grdemma',
    'Hellesengtjenna',
    'Kammerfosssen',
    'Stranda',
    'Styggs',
    'Bjerkadalen',
    'Tuvhaugen',
    'Bjerkadalen',
    'Storelva-Stillelva',
    'Mellingsdalen',
    'Nesplassen',
    'ksendalsra',
    'Smgevatnet',
    'Komagvrstranda',
    'Indre Iddefjord/Enningdalselva',
    'Svartvannet',
    'Revlingen',
    'Rauerkalven',
    'Rauer',
    'Paradisbukta',
    'Krkstadfjorden',
    'Herflsalta',
    'Gjlertangen',
    'Garntangen',
    'Fjellsbergtangen',
    'Bogenlia',
    'Bjrnevgenlia',
    'Arekilen',
    'Sndre Haugstensen',
    'Tasken',
    'Skipstadsand',
    'Orebukta',
    'Fuglevik',
    'Alshusbukta',
    'Gravningen',
    'Krlen',
    'Viulkastet',
    'Nreimsbekken',
    'Gulsvikelvi',
    'Rankedal',
    'Deifjellia',
    'Vikerfjell',
    'Vikerfjell',
    'Festningen',
    'Bringen',
    'Bukollen',
    'Nordre Dyttholknatten',
    'Middagsknatten',
    'Nevlingkollen',
    'Aurdalsterberga',
    'Sndre Dyttholknatten',
    'Godmatdalen',
    'Karlsy prestegrd',
    'Karlsy prestegrd',
    'Bogen',
    'Srkjosleira',
    'Morfjorden',
    'Morfjorden',
    'Nykvg/Nykan',
    'Srmela',
    'Forfjorden',
    'Nyke - Tussen',
    'Storeidvatnet',
    'Nordre Varnvassdalen',
    'Raudvatnet',
    'Lullefjellet',
    'Eikeland',
    'Hljanmyra',
    'Risysundet',
    'Mosaksla',
    'Bleia',
    'Grnosmyrane',
    'Kvitingsmorki',
    'Srvret',
    'Nordheimsdalen',
    'Hjelmsysandfjorden',
    'Krokelvosen',
    'Drgnismorki-Yttrismorki',
    'Honnsrve',
    'Hyskjet',
    'Hyrokampen',
    'Kallskaret',
    'Nigardsbreen',
    'Augla',
    'Hommedal prestegrdskog',
    'Hya',
    'Storveltlia',
    'Grnnsliane',
    'Lun',
    'Grnlidalen',
    'Solevatn',
    'Husbergya',
    'Viernbukta',
    'Vendelholmene',
    'Vgsdalsliane',
    'Gaulosen',
    'Apoteket',
    'rin',
    'Vikosen',
    'Forfjorddalen',
    'Ratvikvatnet',
    'Lerstadvatnet',
    'Strandvassbotn',
    'Berg',
    'Solgrdhavna',
    'grdselva',
    'Fltten',
    'Hks',
    'Desiderialunden',
    'Brattsen',
    'Lauvsen',
    'Gygrestolen',
    'Gygrestolen',
    'Langedalsfjellet',
    'Tokkei',
    'Tokkei',
    'Tokkei',
    'Gjuvet',
    'Hstad',
    'Fjellstulfjellet',
    'Presttjennmarka',
    'Skasberget',
    'Solfrittkroken',
    'Korpreiret',
    'Lindberget',
    'Gammeldalsberget',
    'Gammeldalsberget',
    'Gammeldalen',
    'Gammeldalen',
    'Nygardsmyrene',
    'Storna',
    'Lemfjellheia',
    'Kjesfjell og Gaupenapen',
    'Tveitersen',
    'Nautarheia',
    'Trendalen',
    'Kyrkjevatna',
    'rdalen',
    'Furebuheii',
    'Rukkevatn',
    'Navassfjell',
    'Nedre Timenes',
    'Kile',
    'Store Snipen',
    'Nrdstebberget',
    'Drdalen',
    'Linehgda',
    'Prestaksla',
    'Skordalen',
    'Luvdalstra',
    'Holmvassdalen',
    'Skibergfjell',
    'Hlandsdalen',
    'Malmya og Malmykalven',
    'Aunskardet-Lakshlhaugen',
    'Stora',
    'Finnssmarka',
    'Erikskulen',
    'Oksdla',
    'Hemrasmarka',
    'Hemna',
    'Krokskogen',
    'Fagermsan',
    'Rundkollen og Sortungsbekken',
    'Skaugumssen',
    'Nordre Skaugumssen',
    'stad',
    'Furusen og Hagahogget',
    'kre og Vikane',
    'Ullensvang',
    'Rstlandet',
    'Ilene',
    'Vikalian',
    'Grura',
    'Grura',
    'Grura',
    'Gullaugtjnnberga',
    'Grytelva',
    'Seterelva',
    'Stersen',
    'Oust',
    'Oust',
    'Rssvassholmen',
    'Melkevatn-Hjertvatn-Brsvatn',
    'Bekkenesholmen',
    'Eidsvatnet',
    'Vikssen',
    'Markhus',
    'Bjnnknuten',
    'Bratterudskogen',
    'Brrfjell',
    'Eidsvoll prestegrd',
    'Eidsvoll prestegrd',
    'Kuyni, Skagyni, Teistholmen og Teistholmskjeret',
    'Kuyni, Skagyni, Teistholmen og Teistholmskjeret',
    'Kvernholmen og Rosmunnen',
    'Kvernholmen og Rosmunnen',
    'Eidsvoll prestegrd',
    'Bogslunden',
    'Husebyskogen',
    'Rdssen',
    'Eime',
    'Heglane',
    'Pasvik',
    'Rdholman',
    'Deset',
    'Hisdalen',
    'Stormyra (Jgervatn)',
    'Faueldalen',
    'Myrvatn',
    'Sommervatnet',
    'Frilset',
    'Isi',
    'Enli',
    'Reiersen',
    'Grnliparken',
    'Telemarkslunden og Ekebylunden',
    'Indre Viksfjord',
    'Strsjen-Prestyan',
    'Bjrnberga og Isteren'
  ],
  NRS: [
    'Skorpa fuglereservat',
    'Blomstrandhamna fuglereservat',
    'Hermansenya fuglereservat',
    'Forlandsyane fuglereservat',
    'Forlandsyane fuglereservat',
    'Plankeholmane fuglereservat',
    'Olsholmen fuglereservat',
    'Dunyane fuglereservat',
    'Srkapp fuglereservat',
    'Srkapp fuglereservat',
    'Srkapp fuglereservat',
    'Moffen naturreservat',
    'Hopen naturreservat',
    'Nordaust-Svalbard naturreservat',
    'Nordaust-Svalbard naturreservat',
    'Nordaust-Svalbard naturreservat',
    'Sraust-Svalbard naturreservat',
    'Srkapp fuglereservat',
    'Srkapp fuglereservat',
    'Srkapp fuglereservat',
    'Srkapp fuglereservat',
    'Srkapp fuglereservat',
    'Srkapp fuglereservat',
    'Srkapp fuglereservat',
    'Kapp Linn fuglereservat',
    'Gsyane fuglereservat',
    'Forlandsyane fuglereservat',
    'Kongsfjorden fuglereservat',
    'Kongsfjorden fuglereservat',
    'Kongsfjorden fuglereservat',
    'Kongsfjorden fuglereservat',
    'Ossian Sars naturreservat',
    'Guissezholmen fuglereservat',
    'Moseya fuglereservat',
    'Isyane fuglereservat',
    'Isyane fuglereservat',
    'Boheman fuglereservat',
    'Boheman fuglereservat',
    'Bjrnya naturreservat'
  ],
  P: [
    'Helin plantepark',
    'Bugynes'
  ],
  PDO: [
    'Einarsneset',
    'Kviljo',
    'Steinodden',
    'Berg',
    'Frydensborg',
    'rstvethalvya',
    'Melsom',
    'Melsom',
    'Karljohansvern',
    'Karljohansvern'
  ],
  PD: [
    'Nordkapp m/Hornvika'
  ],
  PO: [
    'Linderud Grd',
    'Sakrisodden',
    'Bergssen',
    'Stave',
    'Granyen',
    'Kviljo',
    'Kviljo',
    'Einarsneset',
    'Lavollskjosen',
    'Vgstranda',
    'Katterompa',
    'Padda',
    'Fyrsteilene',
    'Krogshavn',
    'Malmhella',
    'Risya',
    'Jrstrendene',
    'Reime',
    'Ulvya',
    'Holtan',
    'Karlsvika',
    'Reverompa',
    'Sandvikbukta',
    'Snstegrd',
    'Mellomya',
    'Banesen',
    'Hellvik gamle brygge'
  ]
}

const MainSearchBox = props => (
  <div style={{ width: '100%' }}>
    <AutoComplete
      hintText='Søk i Naturtyper'
      hintStyle={{ color: '#aaaaaa' }}
      filter={AutoComplete.fuzzyFilter}
      dataSource={vo.NR}
      maxSearchResults={15}
      underlineShow={false}
      onUpdateInput={props.onUpdateSearch}
      fullWidth
    />
  </div>
)

MainSearchBox.propTypes = {
  onUpdateSearch: PropTypes.func.isRequired
}

export default MainSearchBox
